"""A short quote for the top of the email, one a day.

The list is shuffled once, in a fixed order, and each day takes the next
one, so a quote doesn't come back until every other one has had its turn
and neighboring days draw from different places.
"""
from __future__ import annotations

import random
from datetime import date

QUOTES = [
    # Chinese
    ("Failure is the mother of success.", "Chinese proverb"),
    ("Sharpening the knife does not delay the cutting of wood.", "Chinese proverb"),
    ("Seeing once is better than hearing a hundred times.", "Chinese proverb"),
    ("Among three people walking, one will be my teacher.", "Confucius"),
    ("Grind an iron rod long enough and it becomes a needle.", "Chinese proverb"),
    ("Better to be broken jade than intact roof tile.", "Chinese proverb"),
    ("When drinking water, remember the spring.", "Chinese proverb"),
    ("Ask and be a fool for five minutes; don't and be one forever.", "Chinese proverb"),
    ("Diligence makes up for lack of talent.", "Chinese proverb"),
    ("To see a thousand miles, climb one more floor.", "Chinese proverb"),
    ("The sea welcomes a hundred rivers.", "Chinese proverb"),
    ("An inch of time is worth an inch of gold.", "Chinese proverb"),
    ("While the green hills remain, there will always be firewood.", "Chinese proverb"),
    ("A loss may turn out to be a gain.", "Chinese proverb"),
    ("After the bitter comes the sweet.", "Chinese proverb"),
    ("Learning without thought is labor lost.", "Confucius"),
    ("Haste does not reach the goal.", "Confucius"),
    ("Only in winter do you see which pines stay green.", "Confucius"),
    ("Strong winds reveal the sturdy grass.", "Chinese proverb"),
    ("True gold does not fear the fire.", "Chinese proverb"),
    ("Fix the roof before the rain.", "Chinese proverb"),
    ("One flower does not make spring.", "Chinese proverb"),
    ("The carp that leaps the Dragon Gate becomes a dragon.", "Chinese proverb"),
    ("A drop of kindness is repaid with a spring.", "Chinese proverb"),
    ("Flow with whatever may happen, and let your mind be free.", "Zhuangzi"),
    ("He who loves others is loved by others.", "Mencius"),
    ("Ten years to grow a tree, a hundred to raise a person.", "Guanzi"),
    ("Read ten thousand books, walk ten thousand miles.", "Chinese proverb"),
    ("Small streams gather into rivers.", "Chinese proverb"),
    ("After rain, the sky clears.", "Chinese proverb"),
    ("When winter goes, spring comes.", "Chinese proverb"),
    ("Beyond the willows and flowers, another village appears.", "Lu You"),
    ("With time and patience, the mulberry leaf becomes silk.", "Chinese proverb"),
    ("Three cobblers together outwit a sage.", "Chinese proverb"),
    ("When everyone gathers wood, the fire burns high.", "Chinese proverb"),
    ("One chopstick breaks easily; a bundle does not.", "Chinese proverb"),
    ("One tree does not make a forest.", "Chinese proverb"),
    ("Live to old age, learn to old age.", "Chinese proverb"),
    ("Learning is like rowing upstream; not to advance is to drop back.", "Chinese proverb"),
    ("The plan for the day begins in the morning.", "Chinese proverb"),
    ("Diligence is the path up the mountain of books.", "Chinese proverb"),
    ("Every trade has its master.", "Chinese proverb"),
    ("No gold is pure and no person perfect.", "Chinese proverb"),
    ("Good food never fears arriving late.", "Chinese proverb"),
    ("Slow work yields fine craft.", "Chinese proverb"),
    ("Happiness is the absence of striving for happiness.", "Zhuangzi"),
    ("Whoever cannot smile should not open a shop.", "Chinese proverb"),
    ("Good medicine tastes bitter.", "Chinese proverb"),
    ("Read a book a hundred times and its meaning appears.", "Chinese proverb"),
    ("When the cart reaches the mountain, a path will appear.", "Chinese proverb"),
    ("When the boat reaches the bridge, it will straighten out.", "Chinese proverb"),
    ("Distance tests a horse's strength; time reveals a person's heart.", "Chinese proverb"),
    ("Nothing in the world is hard for someone who sets their heart to it.", "Chinese proverb"),
    ("It is not too late to mend the pen after a sheep is lost.", "Chinese proverb"),
    ("One step, one footprint.", "Chinese proverb"),
    ("Fall into a pit, and you gain in wit.", "Chinese proverb"),
    ("The waves behind push the waves ahead.", "Chinese proverb"),
    ("Blue is drawn from indigo yet surpasses indigo.", "Xunzi"),
    ("There is no end to learning.", "Chinese proverb"),
    ("The wise seek harmony, not sameness.", "Confucius"),
    ("What you do not wish for yourself, do not do to others.", "Confucius"),
    ("The highest good is like water.", "Laozi"),
    ("He who stands on tiptoe is not steady.", "Laozi"),

    # Japanese
    ("The bamboo that bends is stronger than the oak that resists.", "Japanese proverb"),
    ("Even monkeys fall from trees.", "Japanese proverb"),
    ("One kind word can warm three winter months.", "Japanese proverb"),
    ("Beginning is easy; continuing is hard.", "Japanese proverb"),
    ("Continuity is power.", "Japanese proverb"),
    ("Sit on a stone for three years and it grows warm.", "Japanese proverb"),
    ("After the rain, the ground hardens.", "Japanese proverb"),
    ("A frog in a well knows nothing of the great ocean.", "Japanese proverb"),
    ("Turn disaster into good fortune.", "Japanese proverb"),
    ("Even dust, piled up, becomes a mountain.", "Japanese proverb"),
    ("If you are in a hurry, take the long way around.", "Japanese proverb"),
    ("Fortune comes to the house that laughs.", "Japanese proverb"),
    ("To lose is to win.", "Japanese proverb"),
    ("A clever hawk hides its talons.", "Japanese proverb"),
    ("Time flies like an arrow.", "Japanese proverb"),
    ("The plan for the year begins on its first morning.", "Japanese proverb"),
    ("Failure is the seed of success.", "Japanese proverb"),
    ("Ten people, ten colors.", "Japanese proverb"),
    ("One time, one meeting.", "Japanese proverb"),
    ("Undefeated by the rain, undefeated by the wind.", "Miyazawa Kenji"),
    ("Do nothing which is of no use.", "Miyamoto Musashi"),
    ("Perceive that which cannot be seen with the eye.", "Miyamoto Musashi"),
    ("Vision without action is a daydream. Action without vision is a nightmare.", "Japanese proverb"),
    ("Think lightly of yourself and deeply of the world.", "Miyamoto Musashi"),
    ("Do not regret what you have done.", "Miyamoto Musashi"),
    ("Accept everything just the way it is.", "Miyamoto Musashi"),

    # Korean
    ("After hardship comes happiness.", "Korean proverb"),
    ("Even when the sky falls, there is a way out.", "Korean proverb"),
    ("Starting is half the work.", "Korean proverb"),
    ("If the words you give are kind, the words you get are kind.", "Korean proverb"),
    ("Dig one well and you will find water.", "Korean proverb"),
    ("Tap even a stone bridge before you cross it.", "Korean proverb"),
    ("A tiger leaves its skin; a person leaves a name.", "Korean proverb"),

    # Arabic
    ("He who strives, finds.", "Arabic proverb"),
    ("Whoever sows will reap.", "Arabic proverb"),
    ("Learning in youth is carving in stone.", "Arabic proverb"),
    ("A friend is known in hard times.", "Arabic proverb"),
    ("One hand cannot clap.", "Arabic proverb"),
    ("Patience is the key to relief.", "Arabic proverb"),
    ("He who asks does not lose his way.", "Arabic proverb"),
    ("A little that lasts beats a lot that stops.", "Arabic proverb"),
    ("The dogs bark, but the caravan moves on.", "Arabic proverb"),
    ("Do good and throw it in the sea.", "Arabic proverb"),
    ("The best speech is brief and meaningful.", "Arabic proverb"),
    ("Visit seldom and love will grow.", "Arabic proverb"),
    ("Choose the neighbor before the house, the companion before the road.", "Arabic proverb"),
    ("He who seeks greatness stays awake at night.", "Arabic proverb"),
    ("Necessity is the mother of invention.", "Arabic proverb"),
    ("Kindness is never lost.", "Arabic proverb"),
    ("Ask the experienced, not the learned.", "Arabic proverb"),
    ("Knowledge is light; ignorance is darkness.", "Arabic proverb"),
    ("A book is a garden carried in the pocket.", "Arabic proverb"),
    ("Not all that a man wishes does he obtain.", "Al-Mutanabbi"),
    ("The winds blow against what the ships desire.", "Al-Mutanabbi"),
    ("Your pain is the breaking of the shell that encloses your understanding.", "Kahlil Gibran"),
    ("Out of suffering have emerged the strongest souls.", "Kahlil Gibran"),
    ("He who does not know the falcon will roast it.", "Arabic proverb"),
    ("A wise enemy is better than a foolish friend.", "Arabic proverb"),
    ("Your friend is who tells you the truth, not who agrees.", "Arabic proverb"),
    ("Contentment is a treasure that never runs out.", "Arabic proverb"),
    ("Drop by drop, a flood forms.", "Arabic proverb"),
    ("Time is a sword; if you do not cut it, it cuts you.", "Arabic proverb"),
    ("Throw stones at the moon and you will master the sling.", "Arabic proverb"),
    ("A skill is a treasure that never runs out.", "Arabic proverb"),
    ("Every faller has a catcher.", "Arabic proverb"),
    ("Knowledge raises a house without pillars.", "Arabic proverb"),
    ("Yesterday is but today's memory, and tomorrow is today's dream.", "Kahlil Gibran"),
    ("Work is love made visible.", "Kahlil Gibran"),
    ("Perplexity is the beginning of knowledge.", "Kahlil Gibran"),
    ("In the sweetness of friendship let there be laughter.", "Kahlil Gibran"),
    ("The deeper that sorrow carves into your being, the more joy you can contain.", "Kahlil Gibran"),
    ("You cannot cover the sun with a sieve.", "Arabic proverb"),
    ("Whoever wants honey must endure the bee's sting.", "Arabic proverb"),
    ("What comes from the heart reaches the heart.", "Arabic proverb"),
    ("He who seeks a friend without flaws stays friendless.", "Arabic proverb"),
    ("The best course is the middle one.", "Arabic proverb"),
    ("He who lives will see.", "Arabic proverb"),
    ("Whoever fears climbing mountains lives forever among the pits.", "Abu al-Qasim al-Shabbi"),
    ("Give the bread to the baker, even if he eats half.", "Arabic proverb"),
]

# A fixed shuffle, so the order is the same on every run. Adding quotes
# reshuffles it, which is fine.
_ORDER = list(range(len(QUOTES)))
random.Random("portland-quotes").shuffle(_ORDER)


def for_day(day: date) -> tuple[str, str]:
    """(quote, who said it) for `day`. The same day always gets the same one."""
    return QUOTES[_ORDER[day.toordinal() % len(QUOTES)]]
